// <auto-generated />
using System;
using JTX_Ecom.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JTX_Ecom.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251107033923_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JTX_Ecom.Models.Concert", b =>
                {
                    b.Property<int>("ConcertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConcertId"));

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("ConcertId");

                    b.HasIndex("EventDate");

                    b.HasIndex("Genre");

                    b.HasIndex("VenueId");

                    b.ToTable("Concerts");

                    b.HasData(
                        new
                        {
                            ConcertId = 1,
                            Artist = "Various Rock Artists",
                            AvailableTickets = 15000,
                            BasePrice = 89.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The biggest rock festival of the year featuring top rock bands",
                            EventDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTime = new DateTime(2025, 3, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Rock",
                            ImageUrl = "/assets/images/concerts/concert1.jpg",
                            IsActive = true,
                            Title = "Rock Festival 2025",
                            TotalTickets = 20000,
                            VenueId = 1
                        },
                        new
                        {
                            ConcertId = 2,
                            Artist = "Top Pop Stars",
                            AvailableTickets = 18000,
                            BasePrice = 125.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A spectacular pop music experience with chart-topping artists",
                            EventDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTime = new DateTime(2025, 4, 5, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Pop",
                            ImageUrl = "/assets/images/concerts/concert2.jpg",
                            IsActive = true,
                            Title = "Pop Extravaganza",
                            TotalTickets = 19000,
                            VenueId = 2
                        },
                        new
                        {
                            ConcertId = 3,
                            Artist = "Jazz Ensemble",
                            AvailableTickets = 450,
                            BasePrice = 65.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "An intimate evening of smooth jazz and soul",
                            EventDate = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTime = new DateTime(2025, 4, 20, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Jazz",
                            ImageUrl = "/assets/images/concerts/concert3.jpg",
                            IsActive = true,
                            Title = "Jazz Night Live",
                            TotalTickets = 500,
                            VenueId = 3
                        },
                        new
                        {
                            ConcertId = 4,
                            Artist = "Top EDM DJs",
                            AvailableTickets = 9500,
                            BasePrice = 149.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ultimate EDM experience with world-class DJs",
                            EventDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTime = new DateTime(2025, 5, 10, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Electronic",
                            ImageUrl = "/assets/images/concerts/concert4.jpg",
                            IsActive = true,
                            Title = "Electronic Dance Night",
                            TotalTickets = 10000,
                            VenueId = 4
                        },
                        new
                        {
                            ConcertId = 5,
                            Artist = "Country Legends",
                            AvailableTickets = 4200,
                            BasePrice = 79.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Celebrating country music heritage with legendary performers",
                            EventDate = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTime = new DateTime(2025, 6, 2, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Country",
                            ImageUrl = "/assets/images/concerts/concert5.jpg",
                            IsActive = true,
                            Title = "Country Music Fest",
                            TotalTickets = 4400,
                            VenueId = 5
                        },
                        new
                        {
                            ConcertId = 6,
                            Artist = "Hip Hop All-Stars",
                            AvailableTickets = 17500,
                            BasePrice = 95.00m,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The hottest hip hop artists live on stage",
                            EventDate = new DateTime(2025, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EventTime = new DateTime(2025, 6, 21, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            Genre = "Hip Hop",
                            ImageUrl = "/assets/images/concerts/concert6.jpg",
                            IsActive = true,
                            Title = "Hip Hop Summit",
                            TotalTickets = 19000,
                            VenueId = 6
                        });
                });

            modelBuilder.Entity("JTX_Ecom.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerEmail");

                    b.HasIndex("OrderDate");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("JTX_Ecom.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("ConcertId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("SoldAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TicketType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TicketId");

                    b.HasIndex("ConcertId");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.HasIndex("TicketNumber")
                        .IsUnique();

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("JTX_Ecom.Models.Venue", b =>
                {
                    b.Property<int>("VenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenueId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VenueId");

                    b.HasIndex("City");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            VenueId = 1,
                            Address = "4 Pennsylvania Plaza",
                            Capacity = 20000,
                            City = "New York",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Madison Square Garden",
                            PhoneNumber = "(212) 465-6741",
                            State = "NY",
                            ZipCode = "10001"
                        },
                        new
                        {
                            VenueId = 2,
                            Address = "1111 S Figueroa St",
                            Capacity = 19000,
                            City = "Los Angeles",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Staples Center",
                            PhoneNumber = "(213) 742-7100",
                            State = "CA",
                            ZipCode = "90015"
                        },
                        new
                        {
                            VenueId = 3,
                            Address = "131 W 3rd St",
                            Capacity = 500,
                            City = "Chicago",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Blue Note",
                            PhoneNumber = "(312) 555-0123",
                            State = "IL",
                            ZipCode = "60601"
                        },
                        new
                        {
                            VenueId = 4,
                            Address = "1 Brickell City Centre",
                            Capacity = 10000,
                            City = "Miami",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Ultra Arena",
                            PhoneNumber = "(305) 555-0199",
                            State = "FL",
                            ZipCode = "33131"
                        },
                        new
                        {
                            VenueId = 5,
                            Address = "2804 Opryland Dr",
                            Capacity = 4400,
                            City = "Nashville",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Grand Ole Opry",
                            PhoneNumber = "(615) 871-6779",
                            State = "TN",
                            ZipCode = "37214"
                        },
                        new
                        {
                            VenueId = 6,
                            Address = "620 Atlantic Ave",
                            Capacity = 19000,
                            City = "Brooklyn",
                            Country = "USA",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Barclays Center",
                            PhoneNumber = "(917) 618-6100",
                            State = "NY",
                            ZipCode = "11217"
                        });
                });

            modelBuilder.Entity("JTX_Ecom.Models.Concert", b =>
                {
                    b.HasOne("JTX_Ecom.Models.Venue", "Venue")
                        .WithMany("Concerts")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("JTX_Ecom.Models.Ticket", b =>
                {
                    b.HasOne("JTX_Ecom.Models.Concert", "Concert")
                        .WithMany("Tickets")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("JTX_Ecom.Models.Order", "Order")
                        .WithMany("Tickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Concert");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("JTX_Ecom.Models.Concert", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("JTX_Ecom.Models.Order", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("JTX_Ecom.Models.Venue", b =>
                {
                    b.Navigation("Concerts");
                });
#pragma warning restore 612, 618
        }
    }
}
